/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OrderService } from "../order.service";
import { OrderCreateInput } from "./OrderCreateInput";
import { Order } from "./Order";
import { OrderFindManyArgs } from "./OrderFindManyArgs";
import { OrderWhereUniqueInput } from "./OrderWhereUniqueInput";
import { OrderUpdateInput } from "./OrderUpdateInput";
import { OrderHistoryFindManyArgs } from "../../orderHistory/base/OrderHistoryFindManyArgs";
import { OrderHistory } from "../../orderHistory/base/OrderHistory";
import { OrderHistoryWhereUniqueInput } from "../../orderHistory/base/OrderHistoryWhereUniqueInput";
import { AssignOrderDto } from "../AssignOrderDto";

export class OrderControllerBase {
  constructor(protected readonly service: OrderService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Order })
  async createOrder(@common.Body() data: OrderCreateInput): Promise<Order> {
    return await this.service.createOrder({
      data: data,
      select: {
        contactNumber: true,
        createdAt: true,
        customerName: true,
        deadline: true,
        deliveryAddress: true,
        deliveryPerson: true,
        estimatedDeliveryTime: true,
        id: true,
        orderItems: true,
        orderNumber: true,
        specialInstructions: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Order] })
  @ApiNestedQuery(OrderFindManyArgs)
  async orders(@common.Req() request: Request): Promise<Order[]> {
    const args = plainToClass(OrderFindManyArgs, request.query);
    return this.service.orders({
      ...args,
      select: {
        contactNumber: true,
        createdAt: true,
        customerName: true,
        deadline: true,
        deliveryAddress: true,
        deliveryPerson: true,
        estimatedDeliveryTime: true,
        id: true,
        orderItems: true,
        orderNumber: true,
        specialInstructions: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async order(
    @common.Param() params: OrderWhereUniqueInput
  ): Promise<Order | null> {
    const result = await this.service.order({
      where: params,
      select: {
        contactNumber: true,
        createdAt: true,
        customerName: true,
        deadline: true,
        deliveryAddress: true,
        deliveryPerson: true,
        estimatedDeliveryTime: true,
        id: true,
        orderItems: true,
        orderNumber: true,
        specialInstructions: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOrder(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() data: OrderUpdateInput
  ): Promise<Order | null> {
    try {
      return await this.service.updateOrder({
        where: params,
        data: data,
        select: {
          contactNumber: true,
          createdAt: true,
          customerName: true,
          deadline: true,
          deliveryAddress: true,
          deliveryPerson: true,
          estimatedDeliveryTime: true,
          id: true,
          orderItems: true,
          orderNumber: true,
          specialInstructions: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Order })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOrder(
    @common.Param() params: OrderWhereUniqueInput
  ): Promise<Order | null> {
    try {
      return await this.service.deleteOrder({
        where: params,
        select: {
          contactNumber: true,
          createdAt: true,
          customerName: true,
          deadline: true,
          deliveryAddress: true,
          deliveryPerson: true,
          estimatedDeliveryTime: true,
          id: true,
          orderItems: true,
          orderNumber: true,
          specialInstructions: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/orderHistories")
  @ApiNestedQuery(OrderHistoryFindManyArgs)
  async findOrderHistories(
    @common.Req() request: Request,
    @common.Param() params: OrderWhereUniqueInput
  ): Promise<OrderHistory[]> {
    const query = plainToClass(OrderHistoryFindManyArgs, request.query);
    const results = await this.service.findOrderHistories(params.id, {
      ...query,
      select: {
        createdAt: true,
        deliveryExperienceRating: true,
        id: true,

        order: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orderHistories")
  async connectOrderHistories(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: OrderHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderHistories: {
        connect: body,
      },
    };
    await this.service.updateOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orderHistories")
  async updateOrderHistories(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: OrderHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderHistories: {
        set: body,
      },
    };
    await this.service.updateOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orderHistories")
  async disconnectOrderHistories(
    @common.Param() params: OrderWhereUniqueInput,
    @common.Body() body: OrderHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orderHistories: {
        disconnect: body,
      },
    };
    await this.service.updateOrder({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/woocommerce/orders/assignOrder")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async AssignOrderToDeliveryPerson(
    @common.Body()
    body: AssignOrderDto
  ): Promise<string> {
    return this.service.AssignOrderToDeliveryPerson(body);
  }

  @common.Get("/:id/assign-woo-commerce-order")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async AssignWooCommerceOrder(
    @common.Body()
    body: AssignOrderDto
  ): Promise<string> {
    return this.service.AssignWooCommerceOrder(body);
  }

  @common.Get("/woocommerce/orders")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async FetchWooCommerceOrders(
    @common.Body()
    body: AssignOrderDto
  ): Promise<string[]> {
    return this.service.FetchWooCommerceOrders(body);
  }

  @common.Patch("/woocommerce/orders/updateStatus")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async UpdateOrderStatus(
    @common.Body()
    body: AssignOrderDto
  ): Promise<string> {
    return this.service.UpdateOrderStatus(body);
  }
}
